# This rule is not used by the project pod-sniffer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over capture.io.github.bibizyann.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: pod-sniffer
    app.kubernetes.io/managed-by: kustomize
  name: packetcapture-admin-role
rules:
- apiGroups:
  - capture.io.github.bibizyann
  resources:
  - packetcaptures
  verbs:
  - '*'
- apiGroups:
  - capture.io.github.bibizyann
  resources:
  - packetcaptures/status
  verbs:
  - get
